### ISSUE TITLE
gazebo simulation waypoints in different z axis

### ISSUE THREAD

**Issue by 15707397862** [KumarRobotics/kr_autonomous_flight#183]
I tried to set some wappoints of different heights in the my gazebo world, but it seems that the UAV cannot move on z axis. Can someone help me.
![2022-12-09 17-44-30 的屏幕截图](https://user-images.githubusercontent.com/86184311/206675151-dad53b36-fb25-427e-bc1c-fe766415c8eb.png)

**Comment by XuRobotics** [comment]
The default mode is 2D planning. You will need to do the following to enable 3D planning mode

Open the file tracker_params_mp.yaml (https://github.com/KumarRobotics/kr_autonomous_flight/blob/master/autonomy_core/control/control_launch/config/tracker_params_mp.yaml).

You will need to set **use_3d_local** and **use_3d_global** to true. 

You can modify **vertical_semi_fov** parameter so that the UAV always plans in the sensor vertical field of view to guarantee safety (but may result in more failures due to limited motion primitives). 

We are developing a new more capable and efficient 3D planning algorithm that will soon be merged back to the master branch, stay tuned!

**Comment by 15707397862** [comment]
thank u sir, and i will try it late. i hope you are in good health at this special time.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KumarRobotics/kr_autonomous_flight"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月17日(星期六) 上午6:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KumarRobotics/kr_autonomous_flight] gazebo simulation waypoints in different z axis (Issue #183)





 
The default mode is 2D planning. You will need to do the following to enable 3D planning mode
 
Open the file tracker_params_mp.yaml (https://github.com/KumarRobotics/kr_autonomous_flight/blob/master/autonomy_core/control/control_launch/config/tracker_params_mp.yaml).
 
You will need to set use_3d_local and use_3d_global to true.
 
You can modify vertical_semi_fov parameter so that the UAV always plans in the sensor vertical field of view to guarantee safety (but may result in more failures due to limited motion primitives).
 
We are developing a new more capable and efficient 3D planning algorithm that will soon be merged back to the master branch, stay tuned!
